services:

  preprocess:
    image: mavroudo/siesta-preprocess
    ports:
      - "8000:8000"
      - "4040:4040"
    networks:
      - siesta-net
    volumes:
      - preprocesses:/app/pythonAPI/dbSQL
      - ./input:/app/pythonAPI/uploadedfiles
    environment:
      s3accessKeyAws: minioadmin
      s3ConnectionTimeout: 600000
      s3endPointLoc: http://minio:9000
      s3secretKeyAws: minioadmin
      kafkaBroker: http://kafka:9092
      kafkaTopic: test
      POSTGRES_ENDPOINT: postgres:5432/metrics
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin

  minio:
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - siesta-net
    depends_on:
      - createbuckets


  createbuckets: #automatically creates the required bucket
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      export MC_HOST_myminio=http://minioadmin:minioadmin@minio:9000;
      /usr/bin/mc mb myminio/siesta;
      /usr/bin/mc policy download myminio/siesta;
      exit 0;
      "
    networks:
      - siesta-net

  cbdeclare-simple:
    image: balaktsis/siesta-cbdeclare:latest
    container_name: cbdeclare-simple
    networks:
      - siesta-net
    volumes:
      - ./output:/app/output
    environment:
      # # S3 Configuration (uses defaults from image)
      # s3endPointLoc: http://minio:9000
      # # Mining parameters
      LOG_NAME: bpic2012
      SUPPORT: 0.1

  cbdeclare-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cbdeclare
    environment:
      - s3accessKeyAws=minioadmin
      - s3ConnectionTimeout=600000
      - s3endPointLoc=http://unicorn.csd.auth.gr:9000
      - s3secretKeyAws=minioadmin
      - JAVA_TOOL_OPTIONS=-XX:-UseContainerSupport --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.time.zone=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED
    volumes:
      - ./output:/app/output
    entrypoint:    
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --driver-memory
      - 10g
      - --conf
      - spark.eventLog.enabled=true
      - --conf
      - spark.eventLog.dir=/tmp/spark-events
      - declare.jar
    command: ["-l", "bpic2012", "-h", "true", "--support", "0", "--outputPath", "/app/output", "-p", "AND", "-t", "TARGET"]
    # depends_on:
    #   - minio
    networks:
      - siesta-net


networks:
  siesta-net:
    name: siesta-net
#    external: true

volumes:
  minio_storage: {}
  preprocesses: {}
  postgres-data: {}